do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    create role anon nologin;
  end if;

  if not exists (select 1 from pg_roles where rolname = 'authenticated') then
    create role authenticated nologin;
  end if;

  if not exists (select 1 from pg_roles where rolname = 'service_role') then
    create role service_role nologin bypassrls;
  end if;
end
$$;

create schema if not exists maintenance;

create table if not exists maintenance.maintenance (
  id bigint generated by default as identity primary key,
  tanggal_maintenance date not null,
  kode_aset text not null,
  nama_perangkat text not null,
  tipe text,
  lokasi text,
  jenis_kegiatan text,
  durasi integer,
  catatan text,
  created_at timestamp default now()
);

create table if not exists maintenance.assets (
  id bigint generated by default as identity primary key,
  kode_aset text not null unique,
  nama_perangkat text not null,
  tipe text,
  lokasi text,
  status text not null default 'aktif',
  maintenance_interval_months integer not null default 12,
  created_at timestamp default now()
);

create table if not exists maintenance.maintenance_schedule (
  id bigint generated by default as identity primary key,
  asset_id bigint not null references maintenance.assets(id) on delete cascade,
  tanggal_jadwal date not null,
  jenis_kegiatan text not null,
  status text not null default 'terjadwal',
  catatan text,
  created_at timestamp default now()
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'uq_maintenance_tanggal_kode_aset'
  ) then
    alter table maintenance.maintenance
    add constraint uq_maintenance_tanggal_kode_aset
    unique (tanggal_maintenance, kode_aset);
  end if;
end
$$;

create index if not exists idx_maintenance_lokasi on maintenance.maintenance(lokasi);
create index if not exists idx_maintenance_tanggal on maintenance.maintenance(tanggal_maintenance);
create index if not exists idx_assets_lokasi on maintenance.assets(lokasi);
create index if not exists idx_assets_status on maintenance.assets(status);
create index if not exists idx_schedule_asset on maintenance.maintenance_schedule(asset_id);
create index if not exists idx_schedule_tanggal on maintenance.maintenance_schedule(tanggal_jadwal);
create index if not exists idx_schedule_status on maintenance.maintenance_schedule(status);

do $$
begin
  if not exists (
    select 1
    from pg_publication
    where pubname = 'supabase_realtime'
  ) then
    create publication supabase_realtime;
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_publication_rel pr
    join pg_class c on c.oid = pr.prrelid
    join pg_namespace n on n.oid = c.relnamespace
    join pg_publication p on p.oid = pr.prpubid
    where p.pubname = 'supabase_realtime'
      and n.nspname = 'maintenance'
      and c.relname = 'maintenance'
  ) then
    alter publication supabase_realtime add table maintenance.maintenance;
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_publication_rel pr
    join pg_class c on c.oid = pr.prrelid
    join pg_namespace n on n.oid = c.relnamespace
    join pg_publication p on p.oid = pr.prpubid
    where p.pubname = 'supabase_realtime'
      and n.nspname = 'maintenance'
      and c.relname = 'assets'
  ) then
    alter publication supabase_realtime add table maintenance.assets;
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_publication_rel pr
    join pg_class c on c.oid = pr.prrelid
    join pg_namespace n on n.oid = c.relnamespace
    join pg_publication p on p.oid = pr.prpubid
    where p.pubname = 'supabase_realtime'
      and n.nspname = 'maintenance'
      and c.relname = 'maintenance_schedule'
  ) then
    alter publication supabase_realtime add table maintenance.maintenance_schedule;
  end if;
end
$$;

grant usage on schema maintenance to anon, authenticated, service_role;
grant select on maintenance.maintenance to anon;
grant select on maintenance.assets, maintenance.maintenance_schedule to anon;
grant select, insert, update, delete on maintenance.maintenance to authenticated, service_role;
grant select, insert, update, delete on maintenance.assets, maintenance.maintenance_schedule to authenticated, service_role;
grant usage, select on sequence maintenance.maintenance_id_seq to authenticated, service_role;
grant usage, select on sequence maintenance.assets_id_seq, maintenance.maintenance_schedule_id_seq to authenticated, service_role;
grant all on all routines in schema maintenance to anon, authenticated, service_role;
grant all on all sequences in schema maintenance to anon, authenticated, service_role;
alter default privileges for role postgres in schema maintenance grant all on tables to anon, authenticated, service_role;
alter default privileges for role postgres in schema maintenance grant all on routines to anon, authenticated, service_role;
alter default privileges for role postgres in schema maintenance grant all on sequences to anon, authenticated, service_role;

alter table maintenance.maintenance enable row level security;
alter table maintenance.assets enable row level security;
alter table maintenance.maintenance_schedule enable row level security;

drop policy if exists maintenance_select on maintenance.maintenance;
create policy maintenance_select
on maintenance.maintenance
for select
to anon, authenticated, service_role
using (true);

drop policy if exists maintenance_insert on maintenance.maintenance;
create policy maintenance_insert
on maintenance.maintenance
for insert
to authenticated, service_role
with check (auth.uid() is not null);

drop policy if exists maintenance_update on maintenance.maintenance;
create policy maintenance_update
on maintenance.maintenance
for update
to authenticated, service_role
using (auth.uid() is not null)
with check (auth.uid() is not null);

drop policy if exists maintenance_delete on maintenance.maintenance;
create policy maintenance_delete
on maintenance.maintenance
for delete
to authenticated, service_role
using (auth.uid() is not null);

drop policy if exists assets_select on maintenance.assets;
create policy assets_select
on maintenance.assets
for select
to anon, authenticated, service_role
using (true);

drop policy if exists assets_insert on maintenance.assets;
create policy assets_insert
on maintenance.assets
for insert
to authenticated, service_role
with check (auth.uid() is not null);

drop policy if exists assets_update on maintenance.assets;
create policy assets_update
on maintenance.assets
for update
to authenticated, service_role
using (auth.uid() is not null)
with check (auth.uid() is not null);

drop policy if exists assets_delete on maintenance.assets;
create policy assets_delete
on maintenance.assets
for delete
to authenticated, service_role
using (auth.uid() is not null);

drop policy if exists schedule_select on maintenance.maintenance_schedule;
create policy schedule_select
on maintenance.maintenance_schedule
for select
to anon, authenticated, service_role
using (true);

drop policy if exists schedule_insert on maintenance.maintenance_schedule;
create policy schedule_insert
on maintenance.maintenance_schedule
for insert
to authenticated, service_role
with check (auth.uid() is not null);

drop policy if exists schedule_update on maintenance.maintenance_schedule;
create policy schedule_update
on maintenance.maintenance_schedule
for update
to authenticated, service_role
using (auth.uid() is not null)
with check (auth.uid() is not null);

drop policy if exists schedule_delete on maintenance.maintenance_schedule;
create policy schedule_delete
on maintenance.maintenance_schedule
for delete
to authenticated, service_role
using (auth.uid() is not null);

create or replace function maintenance.get_maintenance_filter_options()
returns jsonb
language sql
stable
as $$
  select jsonb_build_object(
    'lokasi',
    coalesce(
      (
        select jsonb_agg(option_value order by option_value)
        from (
          select distinct lokasi as option_value
          from maintenance.maintenance
          where lokasi is not null and lokasi <> ''
        ) lokasi_options
      ),
      '[]'::jsonb
    ),
    'jenis_kegiatan',
    coalesce(
      (
        select jsonb_agg(option_value order by option_value)
        from (
          select distinct jenis_kegiatan as option_value
          from maintenance.maintenance
          where jenis_kegiatan is not null and jenis_kegiatan <> ''
        ) activity_options
      ),
      '[]'::jsonb
    )
  );
$$;

create or replace function maintenance.get_available_maintenance_years(p_lokasi text)
returns table (tahun integer)
language sql
stable
as $$
  select distinct extract(year from tanggal_maintenance)::integer as tahun
  from maintenance.maintenance
  where lokasi = p_lokasi
  order by tahun desc;
$$;

create or replace function maintenance.get_maintenance_dashboard(
  p_lokasi text default null,
  p_date_from date default null,
  p_date_to date default null,
  p_jenis_kegiatan text default null
)
returns jsonb
language sql
stable
as $$
  with filtered as (
    select *
    from maintenance.maintenance
    where (p_lokasi is null or lokasi = p_lokasi)
      and (p_date_from is null or tanggal_maintenance >= p_date_from)
      and (p_date_to is null or tanggal_maintenance <= p_date_to)
      and (p_jenis_kegiatan is null or jenis_kegiatan = p_jenis_kegiatan)
  ),
  yearly as (
    select
      extract(year from tanggal_maintenance)::integer as tahun,
      count(*)::integer as total_maintenance
    from filtered
    group by 1
    order by 1
  ),
  activities as (
    select
      coalesce(jenis_kegiatan, 'tanpa-kategori') as jenis_kegiatan,
      count(*)::integer as total_maintenance
    from filtered
    group by 1
    order by 2 desc, 1 asc
  ),
  top_activity as (
    select jenis_kegiatan
    from activities
    order by total_maintenance desc, jenis_kegiatan asc
    limit 1
  )
  select jsonb_build_object(
    'total_aset',
    coalesce(
      (
        select count(*)::integer
        from maintenance.assets
        where (p_lokasi is null or lokasi = p_lokasi)
      ),
      0
    ),
    'total_maintenance', coalesce((select count(*)::integer from filtered), 0),
    'total_durasi', coalesce((select sum(coalesce(durasi, 0))::integer from filtered), 0),
    'kegiatan_paling_sering', coalesce((select jenis_kegiatan from top_activity), '-'),
    'yearly',
    coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'tahun', tahun,
            'total_maintenance', total_maintenance
          )
          order by tahun
        )
        from yearly
      ),
      '[]'::jsonb
    ),
    'activities',
    coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'jenis_kegiatan', jenis_kegiatan,
            'total_maintenance', total_maintenance
          )
          order by total_maintenance desc, jenis_kegiatan
        )
        from activities
      ),
      '[]'::jsonb
    )
  );
$$;

grant execute on function maintenance.get_maintenance_filter_options() to anon, authenticated, service_role;
grant execute on function maintenance.get_available_maintenance_years(text) to anon, authenticated, service_role;
grant execute on function maintenance.get_maintenance_dashboard(text, date, date, text) to anon, authenticated, service_role;
