do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    create role anon nologin;
  end if;

  if not exists (select 1 from pg_roles where rolname = 'authenticated') then
    create role authenticated nologin;
  end if;

  if not exists (select 1 from pg_roles where rolname = 'service_role') then
    create role service_role nologin bypassrls;
  end if;
end
$$;

create schema if not exists maintenance;

create table if not exists maintenance.maintenance (
  id bigint generated by default as identity primary key,
  tanggal_maintenance date not null,
  kode_aset text not null,
  nama_perangkat text not null,
  tipe text,
  lokasi text,
  jenis_kegiatan text,
  durasi integer,
  catatan text,
  created_at timestamp default now()
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'uq_maintenance_tanggal_kode_aset'
  ) then
    alter table maintenance.maintenance
    add constraint uq_maintenance_tanggal_kode_aset
    unique (tanggal_maintenance, kode_aset);
  end if;
end
$$;

create index if not exists idx_maintenance_lokasi on maintenance.maintenance(lokasi);
create index if not exists idx_maintenance_tanggal on maintenance.maintenance(tanggal_maintenance);

grant usage on schema maintenance to anon, authenticated, service_role;
grant select on maintenance.maintenance to anon;
grant select, insert, update, delete on maintenance.maintenance to authenticated, service_role;
grant usage, select on sequence maintenance.maintenance_id_seq to authenticated, service_role;
grant all on all routines in schema maintenance to anon, authenticated, service_role;
grant all on all sequences in schema maintenance to anon, authenticated, service_role;
alter default privileges for role postgres in schema maintenance grant all on tables to anon, authenticated, service_role;
alter default privileges for role postgres in schema maintenance grant all on routines to anon, authenticated, service_role;
alter default privileges for role postgres in schema maintenance grant all on sequences to anon, authenticated, service_role;

alter table maintenance.maintenance enable row level security;

drop policy if exists maintenance_select on maintenance.maintenance;
create policy maintenance_select
on maintenance.maintenance
for select
to anon, authenticated, service_role
using (true);

drop policy if exists maintenance_insert on maintenance.maintenance;
create policy maintenance_insert
on maintenance.maintenance
for insert
to authenticated, service_role
with check (auth.uid() is not null);

drop policy if exists maintenance_update on maintenance.maintenance;
create policy maintenance_update
on maintenance.maintenance
for update
to authenticated, service_role
using (auth.uid() is not null)
with check (auth.uid() is not null);

drop policy if exists maintenance_delete on maintenance.maintenance;
create policy maintenance_delete
on maintenance.maintenance
for delete
to authenticated, service_role
using (auth.uid() is not null);

create or replace function maintenance.get_maintenance_filter_options()
returns jsonb
language sql
stable
as $$
  select jsonb_build_object(
    'lokasi',
    coalesce(
      (
        select jsonb_agg(option_value order by option_value)
        from (
          select distinct lokasi as option_value
          from maintenance.maintenance
          where lokasi is not null and lokasi <> ''
        ) lokasi_options
      ),
      '[]'::jsonb
    ),
    'jenis_kegiatan',
    coalesce(
      (
        select jsonb_agg(option_value order by option_value)
        from (
          select distinct jenis_kegiatan as option_value
          from maintenance.maintenance
          where jenis_kegiatan is not null and jenis_kegiatan <> ''
        ) activity_options
      ),
      '[]'::jsonb
    )
  );
$$;

create or replace function maintenance.get_available_maintenance_years(p_lokasi text)
returns table (tahun integer)
language sql
stable
as $$
  select distinct extract(year from tanggal_maintenance)::integer as tahun
  from maintenance.maintenance
  where lokasi = p_lokasi
  order by tahun desc;
$$;

create or replace function maintenance.get_maintenance_dashboard(
  p_lokasi text default null,
  p_date_from date default null,
  p_date_to date default null,
  p_jenis_kegiatan text default null
)
returns jsonb
language sql
stable
as $$
  with filtered as (
    select *
    from maintenance.maintenance
    where (p_lokasi is null or lokasi = p_lokasi)
      and (p_date_from is null or tanggal_maintenance >= p_date_from)
      and (p_date_to is null or tanggal_maintenance <= p_date_to)
      and (p_jenis_kegiatan is null or jenis_kegiatan = p_jenis_kegiatan)
  ),
  yearly as (
    select
      extract(year from tanggal_maintenance)::integer as tahun,
      count(*)::integer as total_maintenance
    from filtered
    group by 1
    order by 1
  ),
  activities as (
    select
      coalesce(jenis_kegiatan, 'tanpa-kategori') as jenis_kegiatan,
      count(*)::integer as total_maintenance
    from filtered
    group by 1
    order by 2 desc, 1 asc
  ),
  top_activity as (
    select jenis_kegiatan
    from activities
    order by total_maintenance desc, jenis_kegiatan asc
    limit 1
  )
  select jsonb_build_object(
    'total_maintenance', coalesce((select count(*)::integer from filtered), 0),
    'total_durasi', coalesce((select sum(coalesce(durasi, 0))::integer from filtered), 0),
    'kegiatan_paling_sering', coalesce((select jenis_kegiatan from top_activity), '-'),
    'yearly',
    coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'tahun', tahun,
            'total_maintenance', total_maintenance
          )
          order by tahun
        )
        from yearly
      ),
      '[]'::jsonb
    ),
    'activities',
    coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'jenis_kegiatan', jenis_kegiatan,
            'total_maintenance', total_maintenance
          )
          order by total_maintenance desc, jenis_kegiatan
        )
        from activities
      ),
      '[]'::jsonb
    )
  );
$$;

grant execute on function maintenance.get_maintenance_filter_options() to anon, authenticated, service_role;
grant execute on function maintenance.get_available_maintenance_years(text) to anon, authenticated, service_role;
grant execute on function maintenance.get_maintenance_dashboard(text, date, date, text) to anon, authenticated, service_role;
